// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABFer9qAe1S6lO4l9mWObRN4sjwn-n9T0',
    appId: '1:161430098229:web:c1dc684861309ef937fc7c',
    messagingSenderId: '161430098229',
    projectId: 'career-navigator-ffb7c',
    authDomain: 'career-navigator-ffb7c.firebaseapp.com',
    storageBucket: 'career-navigator-ffb7c.appspot.com',
    measurementId: 'G-H4GM8P5K8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA32mX7ng8DiD5PkWRov3_NUqqY7U83noU',
    appId: '1:161430098229:android:fc66adfb3521522c37fc7c',
    messagingSenderId: '161430098229',
    projectId: 'career-navigator-ffb7c',
    storageBucket: 'career-navigator-ffb7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaXihhACp12fl1NSSB1GCNzbIYtQaOFDo',
    appId: '1:161430098229:ios:e4fdccff476901a637fc7c',
    messagingSenderId: '161430098229',
    projectId: 'career-navigator-ffb7c',
    storageBucket: 'career-navigator-ffb7c.appspot.com',
    iosBundleId: 'com.example.careernavigator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaXihhACp12fl1NSSB1GCNzbIYtQaOFDo',
    appId: '1:161430098229:ios:e4fdccff476901a637fc7c',
    messagingSenderId: '161430098229',
    projectId: 'career-navigator-ffb7c',
    storageBucket: 'career-navigator-ffb7c.appspot.com',
    iosBundleId: 'com.example.careernavigator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABFer9qAe1S6lO4l9mWObRN4sjwn-n9T0',
    appId: '1:161430098229:web:310d09a460c9316a37fc7c',
    messagingSenderId: '161430098229',
    projectId: 'career-navigator-ffb7c',
    authDomain: 'career-navigator-ffb7c.firebaseapp.com',
    storageBucket: 'career-navigator-ffb7c.appspot.com',
    measurementId: 'G-8EMQF2TBW8',
  );
}
